
# This is your Supabase configuration file
project_id = "nfmstsrqfyhpooikhfns"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[functions.pinterest-analytics]
verify_jwt = true

[functions."get-rapidapi-key"]
verify_jwt = false

[functions."set-rapidapi-key"]
verify_jwt = true
