// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfmstsrqfyhpooikhfns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mbXN0c3JxZnlocG9vaWtoZm5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNzE5MjYsImV4cCI6MjA1NzY0NzkyNn0.vwSrJzvsIHuxMOxPEc8JpR6Z75OqHsst7masA58cMng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);